import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import AppFooter from "@/components/AppFooter";

interface GalleryItem {
  id: string;
  prompt: string;
  cost: string;
  category: string;
  createdAt: string;
}

const DEMO_ITEMS: GalleryItem[] = [
  { id: "1", prompt: "A French bakery in Paris with warm earth tones", cost: "0.004", category: "bakery", createdAt: "2026-03-31" },
  { id: "2", prompt: "Dark SaaS landing for a project management tool", cost: "0.005", category: "saas", createdAt: "2026-03-31" },
  { id: "3", prompt: "Minimal developer portfolio with dark mode", cost: "0.003", category: "portfolio", createdAt: "2026-03-30" },
  { id: "4", prompt: "Italian restaurant in Bordeaux with reservations", cost: "0.004", category: "restaurant", createdAt: "2026-03-30" },
  { id: "5", prompt: "Creative agency with case studies and bold design", cost: "0.005", category: "agency", createdAt: "2026-03-29" },
  { id: "6", prompt: "B2B SaaS with enterprise pricing and social proof", cost: "0.006", category: "saas", createdAt: "2026-03-29" },
];

const FILTERS = [
  { label: "All", value: "all" },
  { label: "Bakeries", value: "bakery" },
  { label: "SaaS", value: "saas" },
  { label: "Portfolio", value: "portfolio" },
  { label: "Restaurant", value: "restaurant" },
  { label: "Agency", value: "agency" },
];

export default function Gallery() {
  const navigate = useNavigate();
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState("all");

  useEffect(() => {
    fetch("/api/gallery")
      .then((r) => r.json())
      .then((data) => {
        if (Array.isArray(data) && data.length > 0) {
          setItems(data);
        } else {
          setItems(DEMO_ITEMS);
        }
        setLoading(false);
      })
      .catch(() => {
        setItems(DEMO_ITEMS);
        setLoading(false);
      });
  }, []);

  const filtered = activeFilter === "all"
    ? items
    : items.filter((item) => item.category === activeFilter);

  return (
    <div className="min-h-screen">
      {/* Page Header */}
      <div className="text-center py-16">
        <h1 className="font-[Syne] text-4xl md:text-5xl font-bold text-[#DCE9F5]">
          Built with ArkhosAI
        </h1>
        <p className="mt-4 text-[#7B8FA3] text-lg">
          Real websites, generated by AI in under 2 minutes
        </p>
      </div>

      {/* Filter Bar */}
      <div className="max-w-6xl mx-auto px-6 flex flex-wrap items-center gap-2 mb-10 justify-center">
        {FILTERS.map((filter) => (
          <button
            key={filter.value}
            onClick={() => setActiveFilter(filter.value)}
            className={
              activeFilter === filter.value
                ? "bg-[#FF6B35] text-white rounded-full px-4 py-1.5 text-sm transition-colors"
                : "bg-transparent text-[#DCE9F5]/50 border border-white/10 rounded-full px-4 py-1.5 text-sm hover:border-white/20 transition-colors"
            }
          >
            {filter.label}
          </button>
        ))}
      </div>

      {/* Gallery Grid */}
      <div className="max-w-6xl mx-auto px-6 pb-20">
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="rounded-xl border border-white/5 bg-[#0D1B2A] overflow-hidden">
                <div className="w-full h-48 bg-[#020408] animate-pulse" />
                <div className="p-4 space-y-3">
                  <div className="h-4 w-3/4 rounded bg-white/5 animate-pulse" />
                  <div className="h-3 w-1/2 rounded bg-white/5 animate-pulse" />
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filtered.length === 0 ? (
              <div className="col-span-full text-center py-20">
                <p className="text-[#DCE9F5]/50 text-lg">No {activeFilter} sites yet</p>
                <button
                  onClick={() => navigate("/generate")}
                  className="mt-4 px-6 py-2 bg-[#FF6B35] text-white rounded-lg text-sm hover:bg-[#FF6B35]/90 transition-colors"
                >
                  Be the first to build one
                </button>
              </div>
            ) : (
              filtered.map((item) => (
                <div
                  key={item.id}
                  className="group rounded-xl border border-white/5 bg-[#0D1B2A] overflow-hidden hover:border-[#FF6B35]/30 transition-all duration-300"
                >
                  {/* Scaled iframe preview */}
                  <div className="relative w-full h-48 overflow-hidden bg-[#020408]">
                    <div
                      className="absolute top-0 left-0 w-[400%] h-[400%] border-0 pointer-events-none origin-top-left"
                      style={{ transform: "scale(0.25)" }}
                    >
                      <div className="w-full h-full bg-gradient-to-br from-[#0D1B2A] to-[#020408]" />
                    </div>
                  </div>
                  {/* Card content */}
                  <div className="p-4 space-y-3">
                    <p className="text-sm text-[#DCE9F5] line-clamp-2">{item.prompt}</p>
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-mono text-[#FF6B35]">&euro;{item.cost}</span>
                      <span className="text-xs px-2 py-0.5 rounded-full border border-[#00D4EE]/20 text-[#00D4EE]">
                        {item.category}
                      </span>
                    </div>
                    <button
                      onClick={() => navigate(`/generate?prompt=${encodeURIComponent(item.prompt)}`)}
                      className="w-full text-sm text-center py-2 rounded-lg border border-white/10 text-[#DCE9F5]/70 hover:bg-white/5 hover:text-[#DCE9F5] transition-colors"
                    >
                      Build something like this
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        )}
      </div>

      {/* Footer */}
      <AppFooter />
    </div>
  );
}
